# Generated by Django 4.0.6 on 2023-08-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tourism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromm', models.CharField(max_length=50)),
                ('to', models.CharField(max_length=50)),
                ('departure', models.DateField()),
                ('returnn', models.DateField()),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('image_x', models.ImageField(upload_to='images')),
            ],
        ),
    ]
